### ISSUE TITLE
能否建立一个DOCKER仓库镜像

### ISSUE THREAD

**Issue by cisco6005** [yangjian102621/geek-ai#3]
ARM64的设备，想通过命令行一键拉取镜像，请大神建立一个docker仓库镜像可以吗？

**Comment by yangjian102621** [comment]
我有推送 Arm 架构镜像的，地址是 registry.cn-shenzhen.aliyuncs.com/geekmaster/geekai-web:v4.0.8-arm64

你可以修改 docker-compose.yaml 更改镜像地址。

你也可以使用下面的方式自己打包 Arm docker 镜像：
```shell
cd build
./build.sh v4.0.8 arm64
```
