### ISSUE TITLE
注册页bug

### ISSUE THREAD

**Issue by Youngxj** [yangjian102621/geek-ai#6]
如果注册方式只留一个用户名注册，那么注册页表单将不会显示用户名，需要重新点一个用户名注册label才会出现用户名表单
![image](https://github.com/user-attachments/assets/928dcff7-82d0-47a6-aa2a-47827a39157e)

版本v4.1.3

**Comment by yangjian102621** [comment]
收到，感谢反馈。

**Comment by yangjian102621** [comment]
@Youngxj 已修复，将在 v4.1.4 版本发布更新
